FROM apache/zeppelin:0.12.0

USER root

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN adduser defaultuser
RUN usermod -u 1001 --gid 0 defaultuser

USER defaultuser
WORKDIR /opt/zeppelin/notebooks

EXPOSE 8888